/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 06-dic.-2025 13:59:19 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS beca_id_seq
;

DROP SEQUENCE IF EXISTS beca_requisito_id_seq
;

DROP SEQUENCE IF EXISTS convocatoria_id_seq
;

DROP SEQUENCE IF EXISTS dependencia_economica_id_seq
;

DROP SEQUENCE IF EXISTS documento_id_seq
;

DROP SEQUENCE IF EXISTS estudiante_id_usuario_seq
;

DROP SEQUENCE IF EXISTS formulario_socio_economico_id_seq
;

DROP SEQUENCE IF EXISTS grupo_familiar_id_seq
;

DROP SEQUENCE IF EXISTS ingreso_economico_id_seq
;

DROP SEQUENCE IF EXISTS miembro_familiar_id_seq
;

DROP SEQUENCE IF EXISTS notificacion_id_seq
;

DROP SEQUENCE IF EXISTS personal_administrativo_id_usuario_seq
;

DROP SEQUENCE IF EXISTS postulacion_id_seq
;

DROP SEQUENCE IF EXISTS requisito_id_seq
;

DROP SEQUENCE IF EXISTS residencia_id_seq
;

DROP SEQUENCE IF EXISTS rol_id_seq
;

DROP SEQUENCE IF EXISTS tenencia_vivienda_id_seq
;

DROP SEQUENCE IF EXISTS tenencia_vivienda_id_formulario_seq
;

DROP SEQUENCE IF EXISTS tipo_ocupacion_dependiente_id_seq
;

DROP SEQUENCE IF EXISTS tipo_tenencia_vivienda_id_seq
;

DROP SEQUENCE IF EXISTS tramite_id_seq
;

DROP SEQUENCE IF EXISTS tramite_historial_id_seq
;

DROP SEQUENCE IF EXISTS usuario_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS beca CASCADE
;

DROP TABLE IF EXISTS beca_requisito CASCADE
;

DROP TABLE IF EXISTS convocatoria CASCADE
;

DROP TABLE IF EXISTS dependencia_economica CASCADE
;

DROP TABLE IF EXISTS documento CASCADE
;

DROP TABLE IF EXISTS estado_tramite CASCADE
;

DROP TABLE IF EXISTS estudiante CASCADE
;

DROP TABLE IF EXISTS formulario_socio_economico CASCADE
;

DROP TABLE IF EXISTS grupo_familiar CASCADE
;

DROP TABLE IF EXISTS ingreso_economico CASCADE
;

DROP TABLE IF EXISTS miembro_familiar CASCADE
;

DROP TABLE IF EXISTS notificacion CASCADE
;

DROP TABLE IF EXISTS personal_administrativo CASCADE
;

DROP TABLE IF EXISTS postulacion CASCADE
;

DROP TABLE IF EXISTS requisito CASCADE
;

DROP TABLE IF EXISTS residencia CASCADE
;

DROP TABLE IF EXISTS rol CASCADE
;

DROP TABLE IF EXISTS tenencia_vivienda CASCADE
;

DROP TABLE IF EXISTS tipo_ocupacion_dependiente CASCADE
;

DROP TABLE IF EXISTS tipo_tenencia_vivienda CASCADE
;

DROP TABLE IF EXISTS tramite CASCADE
;

DROP TABLE IF EXISTS tramite_historial CASCADE
;

DROP TABLE IF EXISTS usuario CASCADE
;

/* Create Tables */

CREATE TABLE beca
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"beca_id_seq"'::text)::regclass),
	nombre varchar(100) NOT NULL,
	descripcion varchar(100) NOT NULL,
	codigo varchar(20) NOT NULL,
	version varchar(10) NOT NULL,
	periodo varchar(20) NOT NULL,
	id_convocatoria bigint NOT NULL,
	cupos_disponibles integer NOT NULL
)
;

CREATE TABLE beca_requisito
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"beca_requisito_id_seq"'::text)::regclass),
	id_beca integer NOT NULL,
	id_requisito integer NOT NULL
)
;

CREATE TABLE convocatoria
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"convocatoria_id_seq"'::text)::regclass),
	nombre varchar(100) NOT NULL,
	descripcion varchar(255) NOT NULL,
	fecha_inicio date NOT NULL,
	fecha_fin date NOT NULL
)
;

CREATE TABLE dependencia_economica
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"dependencia_economica_id_seq"'::text)::regclass),
	id_formulario bigint NULL,
	tipo_dependencia varchar(50) NULL,
	nota_ocupacion_dependiente varchar(50) NULL,
	id_ocupacion_dependiente bigint NULL,
	puntaje numeric(3,1) NULL,
	puntaje_total numeric(3,1) NULL
)
;

CREATE TABLE documento
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"documento_id_seq"'::text)::regclass),
	id_tramite bigint NULL,
	tipo_documento varchar(50) NULL,
	nombre_archivo varchar(100) NULL,
	ruta_digital varchar(255) NULL,
	estado_fisico varchar(100) NULL,
	digitalizado_por bigint NULL,
	fecha_presentacion date NULL,
	fecha_digitalizacion date NULL,
	observaciones varchar(255) NULL,
	motivo_rechazo varchar(255) NULL,
	validado_por bigint NULL
)
;

CREATE TABLE estado_tramite
(
	id bigint NOT NULL,
	nombre varchar(50) NULL,
	descripcion varchar(255) NULL
)
;

CREATE TABLE estudiante
(
	id_usuario bigint NOT NULL   DEFAULT NEXTVAL(('"estudiante_id_usuario_seq"'::text)::regclass),
	nro_registro varchar(50) NULL,
	carrera varchar(100) NULL,
	semestre integer NULL
)
;

CREATE TABLE formulario_socio_economico
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"formulario_socio_economico_id_seq"'::text)::regclass),
	id_estudiante bigint NULL,
	validado_por boolean NULL,
	fecha_llenado date NULL,
	completado boolean NULL,
	telefono_referencia varchar(50) NULL,
	comentario_personal varchar(255) NULL,
	observaciones varchar(50) NULL,
	discapacidad boolean NULL,
	comentario_discapacidad varchar(255) NULL,
	otro_beneficio boolean NULL,
	comentario_otro_beneficio varchar(255) NULL,
	lugar_procedencia varchar(100) NULL
)
;

CREATE TABLE grupo_familiar
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"grupo_familiar_id_seq"'::text)::regclass),
	id_formulario bigint NULL,
	cantidad_hijos integer NULL,
	cantidad_familiares integer NOT NULL,
	tiene_hijos boolean NOT NULL,
	puntaje numeric(4,2) NULL,
	puntaje_total numeric(4,2) NULL
)
;

CREATE TABLE ingreso_economico
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"ingreso_economico_id_seq"'::text)::regclass),
	id_dependencia_eco bigint NULL,
	rango_monto varchar(50) NULL,
	puntaje numeric(4,2) NULL
)
;

CREATE TABLE miembro_familiar
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"miembro_familiar_id_seq"'::text)::regclass),
	id_grupo_familiar bigint NULL,
	nombre_completo varchar(100) NULL,
	parentesco varchar(100) NULL,
	edad integer NULL,
	ocupacion varchar(100) NULL,
	observacion varchar(255) NULL
)
;

CREATE TABLE notificacion
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"notificacion_id_seq"'::text)::regclass),
	id_estudiante bigint NULL,
	id_tramite bigint NULL,
	tipo varchar(50) NULL,
	titulo varchar(100) NULL,
	mensaje varchar(255) NULL,
	leido boolean NULL,
	fecha_creacion date NULL,
	fecha_lectura date NULL,
	canal varchar(50) NULL
)
;

CREATE TABLE personal_administrativo
(
	id_usuario bigint NOT NULL   DEFAULT NEXTVAL(('"personal_administrativo_id_usuario_seq"'::text)::regclass),
	cargo varchar(50) NULL,
	departamento varchar(50) NULL,
	activo boolean NULL
)
;

CREATE TABLE postulacion
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"postulacion_id_seq"'::text)::regclass),
	id_estudiante bigint NULL,
	id_convocatoria bigint NULL,
	id_formulario bigint NULL,
	fecha_postulacion date NULL,
	estado_postulado varchar(50) NULL,
	motivo_rechazo varchar(100) NULL,
	posicion_ranking integer NULL,
	puntaje_final numeric(5,2) NULL,
	creado_por bigint NULL,
	id_beca bigint NULL
)
;

CREATE TABLE requisito
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"requisito_id_seq"'::text)::regclass),
	nombre varchar(50) NULL,
	descripcion varchar(50) NULL
)
;

CREATE TABLE residencia
(
	id bigint NULL   DEFAULT NEXTVAL(('"residencia_id_seq"'::text)::regclass),
	id_formulario bigint NULL,
	provincia varchar(50) NULL,
	zona varchar(50) NULL,
	calle varchar(50) NULL,
	cant_banhos integer NULL,
	cant_salas integer NULL,
	cant_dormitorios integer NULL,
	cantt_comedor integer NULL,
	barrio varchar(50) NULL,
	cant_patios integer NULL,
	puntaje_total numeric(4,2) NULL
)
;

CREATE TABLE rol
(
	"Id" bigint NOT NULL   DEFAULT NEXTVAL(('"rol_id_seq"'::text)::regclass),
	nombre varchar(50) NOT NULL,
	descripcion varchar(100) NOT NULL
)
;

CREATE TABLE tenencia_vivienda
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"tenencia_vivienda_id_seq"'::text)::regclass),
	id_formulario bigint NULL   DEFAULT NEXTVAL(('"tenencia_vivienda_id_formulario_seq"'::text)::regclass),
	tipo_tenencia varchar(50) NULL,
	detalle_tenencia varchar(50) NULL,
	puntaje numeric(3,1) NULL,
	puntaje_total numeric(3,1) NULL
)
;

CREATE TABLE tipo_ocupacion_dependiente
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"tipo_ocupacion_dependiente_id_seq"'::text)::regclass),
	id_dependencia_eco bigint NULL,
	nombre varchar(50) NULL,
	archivo_adjuntar varchar(50) NULL,
	puntaje numeric(4,2) NULL
)
;

CREATE TABLE tipo_tenencia_vivienda
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"tipo_tenencia_vivienda_id_seq"'::text)::regclass),
	id_tenencia_vivienda bigint NULL,
	nombre varchar(50) NULL,
	documento_adjuntar varchar(50) NULL,
	puntaje numeric(3,1) NULL
)
;

CREATE TABLE tramite
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"tramite_id_seq"'::text)::regclass),
	id_postulacion bigint NULL,
	codigo varchar(50) NOT NULL,
	fecha_creacion date NOT NULL,
	clasificado varchar(50) NOT NULL,
	fecha_clasificacion date NULL,
	estado_actual bigint NULL
)
;

CREATE TABLE tramite_historial
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"tramite_historial_id_seq"'::text)::regclass),
	id_tramite integer NOT NULL,
	observaciones varchar(10) NOT NULL,
	revisador_por integer NOT NULL,
	fecha_revision date NOT NULL,
	estado_anterior varchar(50) NULL,
	estado_nuevo varchar(50) NULL
)
;

CREATE TABLE usuario
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"usuario_id_seq"'::text)::regclass),
	id_rol bigint NOT NULL,
	nombres varchar(100) NOT NULL,
	apellidos varchar(100) NOT NULL,
	ci varchar(20) NOT NULL,
	telefono varchar(15) NOT NULL,
	email varchar(100) NOT NULL,
	password varchar(100) NOT NULL,
	ciudad varchar(50) NOT NULL,
	fecha_nacimiento date NOT NULL,
	created_at date NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE beca ADD CONSTRAINT "PK_Beca"
	PRIMARY KEY (id)
;

ALTER TABLE beca_requisito ADD CONSTRAINT "PK_Beca Requisito"
	PRIMARY KEY (id)
;

ALTER TABLE convocatoria ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY (id)
;

ALTER TABLE dependencia_economica ADD CONSTRAINT "PK_Dependencia  Economica"
	PRIMARY KEY (id)
;

ALTER TABLE documento ADD CONSTRAINT "PK_Documento"
	PRIMARY KEY (id)
;

ALTER TABLE estado_tramite ADD CONSTRAINT "PK_Estado Tramite"
	PRIMARY KEY (id)
;

ALTER TABLE estudiante ADD CONSTRAINT "PK_Estudiante"
	PRIMARY KEY (id_usuario)
;

ALTER TABLE formulario_socio_economico ADD CONSTRAINT "PK_FormularioSocioEconomico"
	PRIMARY KEY (id)
;

ALTER TABLE grupo_familiar ADD CONSTRAINT "PK_Grupo Familiar"
	PRIMARY KEY (id)
;

ALTER TABLE ingreso_economico ADD CONSTRAINT "PK_Ingreso Economico"
	PRIMARY KEY (id)
;

ALTER TABLE miembro_familiar ADD CONSTRAINT "PK_Miembro Familiar"
	PRIMARY KEY (id)
;

ALTER TABLE notificacion ADD CONSTRAINT "PK_notificacion"
	PRIMARY KEY (id)
;

ALTER TABLE personal_administrativo ADD CONSTRAINT "PK_Personal_Administrativo"
	PRIMARY KEY (id_usuario)
;

ALTER TABLE postulacion ADD CONSTRAINT "PK_Postulacion"
	PRIMARY KEY (id)
;

ALTER TABLE requisito ADD CONSTRAINT "PK_Requisito"
	PRIMARY KEY (id)
;

ALTER TABLE rol ADD CONSTRAINT "PK_Rol"
	PRIMARY KEY ("Id")
;

CREATE INDEX "IXFK_Rol_Usuario" ON rol ("Id" ASC)
;

ALTER TABLE tenencia_vivienda ADD CONSTRAINT "PK_Tenencia Vivienda"
	PRIMARY KEY (id)
;

ALTER TABLE tipo_ocupacion_dependiente ADD CONSTRAINT "PK_Tipo Ocupacion Dependiente"
	PRIMARY KEY (id)
;

ALTER TABLE tipo_tenencia_vivienda ADD CONSTRAINT "PK_Tipo Tenencia Vivienda"
	PRIMARY KEY (id)
;

ALTER TABLE tramite ADD CONSTRAINT "PK_Tramite"
	PRIMARY KEY (id)
;

ALTER TABLE tramite_historial ADD CONSTRAINT "PK_Tramite_Historial"
	PRIMARY KEY (id)
;

ALTER TABLE usuario ADD CONSTRAINT "PK_Usuario"
	PRIMARY KEY (id)
;

ALTER TABLE usuario 
  ADD CONSTRAINT email_unique UNIQUE (email)
;

CREATE INDEX "IXFK_Usuario_Rol" ON usuario (id_rol ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE beca ADD CONSTRAINT "FK_Beca_Convocatoria"
	FOREIGN KEY (id_convocatoria) REFERENCES convocatoria (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE beca_requisito ADD CONSTRAINT "FK_Beca Requisito_Beca"
	FOREIGN KEY (id_beca) REFERENCES beca (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE beca_requisito ADD CONSTRAINT "FK_Beca Requisito_Requisito"
	FOREIGN KEY (id_requisito) REFERENCES requisito (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dependencia_economica ADD CONSTRAINT "FK_Dependencia  Economica_FormularioSocioEconomico"
	FOREIGN KEY (id_formulario) REFERENCES formulario_socio_economico (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE documento ADD CONSTRAINT "FK_Documento_Personal Administtrativo"
	FOREIGN KEY (digitalizado_por) REFERENCES personal_administrativo (id_usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE documento ADD CONSTRAINT "FK_Documento_Personal Administtrativo_02"
	FOREIGN KEY (validado_por) REFERENCES personal_administrativo (id_usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE estudiante ADD CONSTRAINT "FK_Estudiante_Usuario"
	FOREIGN KEY (id_usuario) REFERENCES usuario (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE formulario_socio_economico ADD CONSTRAINT "FK_FormularioSocioEconomico_Estudiante"
	FOREIGN KEY (id_estudiante) REFERENCES estudiante (id_usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE grupo_familiar ADD CONSTRAINT "FK_Grupo Familiar_FormularioSocioEconomico"
	FOREIGN KEY (id_formulario) REFERENCES formulario_socio_economico (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ingreso_economico ADD CONSTRAINT "FK_Ingreso Economico_Dependencia  Economica"
	FOREIGN KEY (id_dependencia_eco) REFERENCES dependencia_economica (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE miembro_familiar ADD CONSTRAINT "FK_Miembro Familiar_Grupo Familiar"
	FOREIGN KEY (id_grupo_familiar) REFERENCES grupo_familiar (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE notificacion ADD CONSTRAINT "FK_Notificacion_Tramite"
	FOREIGN KEY (id_tramite) REFERENCES tramite (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE notificacion ADD CONSTRAINT "FK_Notificacion_Usuario"
	FOREIGN KEY (id_estudiante) REFERENCES usuario (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE personal_administrativo ADD CONSTRAINT "FK_Personal_Administrativo_Usuario"
	FOREIGN KEY (id_usuario) REFERENCES usuario (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE postulacion ADD CONSTRAINT "FK_Postulacion_Beca"
	FOREIGN KEY (id_beca) REFERENCES beca (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE postulacion ADD CONSTRAINT "FK_Postulacion_Convocatoria"
	FOREIGN KEY (id_convocatoria) REFERENCES convocatoria (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE postulacion ADD CONSTRAINT "FK_Postulacion_Estudiante"
	FOREIGN KEY (id_estudiante) REFERENCES estudiante (id_usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE postulacion ADD CONSTRAINT "FK_postulacion_formulario_socio_economico"
	FOREIGN KEY (id_formulario) REFERENCES formulario_socio_economico (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE postulacion ADD CONSTRAINT "FK_Postulacion_Personal Administtrativo"
	FOREIGN KEY (creado_por) REFERENCES personal_administrativo (id_usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE residencia ADD CONSTRAINT "FK_Residencia_FormularioSocioEconomico"
	FOREIGN KEY (id_formulario) REFERENCES formulario_socio_economico (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tenencia_vivienda ADD CONSTRAINT "FK_Tenencia Vivienda_FormularioSocioEconomico"
	FOREIGN KEY (id_formulario) REFERENCES formulario_socio_economico (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tipo_ocupacion_dependiente ADD CONSTRAINT "FK_Tipo Ocupacion Dependiente_Dependencia  Economica"
	FOREIGN KEY (id_dependencia_eco) REFERENCES dependencia_economica (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tipo_tenencia_vivienda ADD CONSTRAINT "FK_Tipo Tenencia Vivienda_Tenencia Vivienda"
	FOREIGN KEY (id_tenencia_vivienda) REFERENCES tenencia_vivienda (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tramite ADD CONSTRAINT "FK_tramite_estado_tramite"
	FOREIGN KEY (estado_actual) REFERENCES estado_tramite (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tramite ADD CONSTRAINT "FK_Tramite_Postulacion"
	FOREIGN KEY (id_postulacion) REFERENCES postulacion (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tramite_historial ADD CONSTRAINT "FK_Tramite_Historial_Personal Administtrativo"
	FOREIGN KEY (revisador_por) REFERENCES personal_administrativo (id_usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tramite_historial ADD CONSTRAINT "FK_Tramite_Historial_Tramite"
	FOREIGN KEY (id_tramite) REFERENCES tramite (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE usuario ADD CONSTRAINT "FK_Usuario_Rol"
	FOREIGN KEY (id_rol) REFERENCES rol ("Id") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE beca_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE beca_requisito_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE convocatoria_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE dependencia_economica_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE documento_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE estudiante_id_usuario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE formulario_socio_economico_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE grupo_familiar_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE ingreso_economico_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE miembro_familiar_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE notificacion_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE personal_administrativo_id_usuario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE postulacion_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE requisito_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE residencia_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE rol_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tenencia_vivienda_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tenencia_vivienda_id_formulario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tipo_ocupacion_dependiente_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tipo_tenencia_vivienda_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tramite_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tramite_historial_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE usuario_id_seq INCREMENT 1 START 1
;
